services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    # environment: 
    #   - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"


volumes:
  jenkins_home:
