version: "3.4"

services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
  # build:
  #   network: host

# networks:
#   host:
#     name: host
#     external: true
    # environment: 
    #   - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"


volumes:
  jenkins_home:
