version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=aaa
      - MYSQL_USER=barcikwhyme
      - MYSQL_PASSWORD=1234 
      - MYSQL_DATABASE=LAB3_TEST
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s

  project:
    image: barcikwhyme/lab3-python-project
    # build: .
    depends_on:
      db:
        condition: service_healthy


